import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import SiteNav from "./components/site-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dusha = localFont({
  src: "./fonts/Dusha.ttf",
  variable: "--font-dusha",
  display: "swap",
});

export const metadata: Metadata = {
  title: "ai mà biết được",
  description: "Generated by create next app",
  icons: {
    icon: "/book.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${dusha.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SiteNav />
        <main>{children}</main>
      </body>
    </html>
  );
}
